<?php

/**
 * PluginmyCurrency
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     pycmam <pycmam@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmyCurrency extends BasemyCurrency
{
    /**
     * @var myCurrency базовая валюта
     */
    protected static $_base = null;

    /**
     * @var myCurrency валюта по-умолчанию
     */
    protected static $_default = null;

    /**
     *
     * @return Currency
     */
    public static function getBaseCurrency()
    {
        if (is_null(self::$_base)) {
            self::$_base = myCurrencyTable::getInstance()->getBaseCurrency();

            if (! self::$_base || ! self::$_base->getCourse()) {
                throw new InvalidArgumentException(__METHOD__ . ': base currency doesn\'t exists');
            }
        }

        return self::$_base;
    }


    /**
     *
     * @return Currency
     */
    public static function getDefaultCurrency()
    {
        if (is_null(self::$_default)) {
            self::$_default = myCurrencyTable::getInstance()->getDefaultCurrency();

            if (! self::$_default || ! self::$_default->getCourse()) {
                throw new InvalidArgumentException(__METHOD__ . ': default currency doesn\'t exists');
            }
        }

        return self::$_default;
    }



    /**
     * Конвертировать из одной валюты в другую
     *
     * @param dsouble $value
     * @param integer $sourceId
     * @param integer $targetId
     */
    public static function convertFromTo($value, $sourceId, $targetId)
    {
        if ($sourceId == $targetId) {
            return $value;
        }

        $source = myCurrencyTable::getInstance()->findOneById((int) $sourceId);
        $target = myCurrencyTable::getInstance()->findOneById((int) $targetId);

        return $source->getCourse() /
            $target->getCourse() * $value;
    }


    /**
     * Конвертировать валюту
     *
     * @param decimal $value
     * @param int     $currencyId
     *
     * return decimal
     */
    public static function convert($value, $currencyId = null)
    {
        $base = self::getBaseCurrency();

        if (is_null($currencyId) || $currencyId == $base->getId()) {
            return $value;
        }

        $currency = myCurrencyTable::getInstance()->findOneById($currencyId);

        return $value * $base->getCourse() / $currency->getCourse();
    }


    /**
     * Конвертировать валюту по аббревиатуре
     *
     * @param decimal $value
     * @param string  $currency
     *
     * return decimal
     */
     public static function convertByAbbr($value, $currency)
     {
         $currency = myCurrencyTable::getInstance()->findOneByAbbreviation($currency);

         if ($currency) {
             return self::convert($value, $currency->getId());
         }

         throw new InvalidArgumentException(__METHOD__.': Invalid currency abbreviation');
     }



    /**
     * Конвертировать из текущей в базовую
     *
     * @param decimal $value
     * @param int     $currencyId
     *
     * return decimal
     */
    public static function convertToBase($value, $currencyId)
    {
        $base = self::getBaseCurrency();

        if (is_null($currencyId) || $currencyId == $base->getId()) {
            return $value;
        }

        $currency = myCurrencyTable::getInstance()->findOneById($currencyId);

        return $value * $currency->getCourse() / $base->getCourse();
    }
}