<?php

/**
 * PluginmyCurrencyTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyCurrencyTable extends myBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyCurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyCurrency');
    }

    /**
     * Возвращает валюту по-умолчанию
     *
     * @return Currency
     */
    public function getDefaultCurrency()
    {
        return $this->queryDefaultCurrency()->fetchOne();
    }

    /**
     * Запрос валюты по-умолчанию
     *
     * @return Doctrine_Query
     */
    public function queryDefaultCurrency()
    {
        return $this->withI18n(null, 'c')
            ->where('c.is_default = ?', true);
    }

    /**
     * Возвращает базовую валюту
     *
     * @return Currency
     */
    public function getBaseCurrency()
    {
        return $this->queryBaseCurrency()
            ->fetchOne();
    }

    /**
     * Запрос базовой валюты
     *
     * @return Doctrine_Query
     */
    public function queryBaseCurrency()
    {
        return $this->withI18n(null, 'c')
            ->where('c.is_base = ?', true);
    }

    /**
     * Список активных валют
     *
     * @return Doctrine_Collection
     */
    public function getActiveCurrency()
    {
        return $this->queryActiveCurrency()
            ->execute();
    }

    /**
     * Запрос списка активных валют
     *
     * @return Doctrine_Query
     */
    public function queryActiveCurrency()
    {
        return $this->withI18n(null, 'c')
            ->where('c.course IS NOT NULL');
    }
}
