<?php

/**
 * PluginmyCurrencyTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyCurrencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyCurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyCurrency');
    }

    /**
     * Create Query
     *
     * @see lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Doctrine_Table::createQuery()
     */
    public function createQuery($alias = 'a')
    {
        return parent::createQuery($alias)
            ->leftJoin($alias . '.Translation t');
    }

    /**
     * Возвращает валюту по-умолчанию
     *
     * @return Currency
     */
    public function getDefaultCurrency()
    {
        return $this->queryDefaultCurrency()->fetchOne();
    }

    /**
     * Запрос валюты по-умолчанию
     *
     * @return Doctrine_Query
     */
    public function queryDefaultCurrency()
    {
        return $this->createQuery('c')
            ->where('c.is_default = ?', true);
    }

    /**
     * Возвращает базовую валюту
     *
     * @return Currency
     */
    public function getBaseCurrency()
    {
        return $this->queryBaseCurrency()
            ->fetchOne();
    }

    /**
     * Запрос базовой валюты
     *
     * @return Doctrine_Query
     */
    public function queryBaseCurrency()
    {
        return $this->createQuery('c')
            ->where('c.is_base = ?', true);
    }

    /**
     * Список активных валют
     *
     * @return Doctrine_Collection
     */
    public function getActiveCurrency()
    {
        return $this->queryActiveCurrency()
            ->execute();
    }

    /**
     * Запрос списка активных валют
     *
     * @return Doctrine_Query
     */
    public function queryActiveCurrency()
    {
        return $this->createQuery('c')
            ->where('c.course IS NOT NULL');
    }
}
